### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by MeRocks2000** [AddstarMC/geSuit#55]
Hello,
I am looking to transfer from BungeeSuite over to your plugin. When I put your main plugin into our Proxy server I get this message in console. http://pastebin.com/LAmZCEAT

I am running the most recent bungee version, as well as the most recent geSuit and Yamler versions, and have even tried a previous version, but no luck.

I know my database info is correct, I can send a copy of the config if you wish. Thanks!

**Comment by alchemistmatt** [comment]
Yes, I think seeing the config file would be useful.  You could pastebin it too, but replace any passwords and optionally server names with fake ones.

**Comment by MeRocks2000** [comment]
http://pastebin.com/NH7ZCW0G

Just to clarify with the databases, they are being run on the same machine, and there is a username that is "2" and a inner database that is "2".  The "password" is replaced with the proper password.

**Comment by alchemistmatt** [comment]
Confirm that you can connect to the database from using the MySql CLI:
`mysql -D 2 -u 2 --password -h localhost`

I find it odd that your error is "Java.sql.SQLException: Access denied for user 'username'@'localhost'" when your username is "2".  That implies that the config.yml file isn't being read properly.

**Comment by MeRocks2000** [comment]
Confirmed.

**Comment by MeRocks2000** [comment]
I find it odd that your error is "Java.sql.SQLException: Access denied for user 'username'@'localhost'" when your username is "2". That implies that the config.yml file isn't being read properly.

Yeah...   really...

**Comment by MeRocks2000** [comment]
So what suggestions do you have so I can get my server back up and running?

**Comment by addstar** [comment]
@MeRocks2000: Your initial error in that output is the important one and it is the one that is causing your problem. @alchemistmatt is right, your config is not being read correctly so it is defaulting to the internal "default" config, which contains "username" as the username.

This error tells me that you are providing an unquoted number as the database name (why are your DB names/users numeric? :confused:) and the Yaml parser is interpreting this as an Integer but is expecting a String:
`Caused by: java.lang.IllegalArgumentException: Can not set java.lang.String field net.cubespace.geSuit.configs.SubConfig.Database.Database to java.lang.Integer`

Just be sure to quote all your usernames and passwords and it should work. In fact, any number that is expected to be a string, just quote it to be safe.

**Comment by MeRocks2000** [comment]
Thanks so much!
