### ISSUE TITLE
geSuit sending new player welcome for players trying to connect to 1.8 server with 1.9 client

### ISSUE THREAD

**Issue by SullyTheUnusual** [AddstarMC/geSuit#56]
I haven't updated to 1.9 yet, but players trying to connect to my server with a 1.9 client trigger the new player announcement.  From the player's perspective, a new player joins and quits right away, never to return.

**Comment by addstar** [comment]
We have not implemented any fix for this, and it's not an easy problem to fix. The events are fired because the player's connection was sent to the back end server but the server just rejects them.

I'm sorry to say, that unfortunately we don't have this issue because we support 1.9 now so it's unlikely we will be able (or have the time) to fix it. When we were only supporting 1.8 clients, we customised BungeeCord to only support 1.8 so 1.9 clients couldn't even attempt to connect. There's possibly plugins out there that might help you implement the same fix. Want you need to do is prevent the player connecting to the proxy in the first place (by having BungeeCord tell the client that only 1.8 is supported).

Sorry I don't have better news for you.
