### ISSUE TITLE
NPE on ServerConnectEvent

### ISSUE THREAD

**Issue by SullyTheUnusual** [AddstarMC/geSuit#59]
Getting an NPE on player login:  http://hastebin.com/ibofokeyuq.avrasm

**Comment by addstar** [comment]
The message `Unable to find player named "lavabazooka" in onlinePlayers list!` means that an earlier error occurred and the player likely had connection issues (check the logs, you will see the player had connection issues or multiple connection attempts). It's almost always a network/client related issue.

It's a well known timing/event issue that works like this:
1. Player makes a connection `#1`
2. Player's client fails to receive the connection acknowledgement, believing it is not connected.
3. Player makes a second (simultaneous) connection `#2`
4. Player's initial connection `#1` times out and disconnects, firing the disconnect event for that player and all plugins react accordingly.
5. Player's second connection `#2` is now in a state of being online, but plugins don't believe the player is online because the disconnect events were fired last.

The only way to deal with this is to throttle connections (or prevent simultaneous connections) so a player can't have this situation occur.

The latest builds of BungeeCord have recently re-implemented the connection throttle, and we suggest using that. We have also discussed putting functionality inside geSuit to prevent these simultaneous connections, but haven't worked on it yet.

**Comment by SullyTheUnusual** [comment]
I checked the connection throttle for BungeeCord, and it's set to 4000.  Is that the preferred setting to help prevent this?
