### ISSUE TITLE
Several errors in the console

### ISSUE THREAD

**Issue by Serux18** [AddstarMC/geSuit#65]
Spigot 1.8.8
Bungeecord #1217
GeSuit (Gesuit, gesuit teleport, gesuit warp): Latest in http://jenkins.addstar.com.au/

Good, for some time, some errors appear in the console when someone uses the teleportation
http://pastebin.com/3D0bjsJ3

There are also other unrelated errors

http://pastebin.com/8vfmZ8dX
http://pastebin.com/jD1NscwT
http://pastebin.com/BFN7qJX6

Thx for read

**Comment by helptiger** [comment]
is /tpall working for you?

**Comment by Serux18** [comment]
No, it doesn't work

**Comment by Serux18** [comment]
http://pastebin.com/dYXVqSyF

In case it serves, this error also appears

**Comment by Segysmundo** [comment]
That's happening to me too.

**Comment by Serux18** [comment]
Can someone help me please?

**Comment by Narimm** [comment]
Someone has manually changed the database so that there is a fk constraint violation...my advice is manually fix the violation...you have a duplicate primary key on a one of the tables somewhere.

Try and backup the data and make a temp db and import it with the exactl create sql and see what errors you got..it will help id the violating data and you can clean it

**Comment by Narimm** [comment]
Also there are some NPE ' s but I would be patching 1.8 version - we dont support old versions
Please update Spigot and geSuit and use the latest versions

**Comment by SeDark** [comment]
I am currently using 1.11.2 / 1.12 on all my servers and this problem continues to occur.

I have deleted my my database on this plugin several times and it happens over and over...
